### ISSUE TITLE
proteger redirection dans minishell

### ISSUE THREAD

**Issue by OlgaKush512** [Lap0u/minishell#47]
./minishell < /dev/random
./minishell < /dev/zero

comment fix:

appeler `isatty(STDIN_FILENO)` si false lire avec GNL, si GNL lis des caracter non imprimable ou \0 renvoyer erreur

**Comment by Lap0u** [comment]
d705af3128e1dfadfd8970edfc9ff40ccd519479 
Fix check isatty, si 0 erreur et quit
