### ISSUE TITLE
Exit

### ISSUE THREAD

**Issue by OlgaKush512** [Lap0u/minishell#52]
![image](https://user-images.githubusercontent.com/92527601/145724202-0c5f6df6-c620-465b-a3a3-039e5b73a697.png)
![image](https://user-images.githubusercontent.com/92527601/145724274-9fcbdc65-eb2e-4f90-bfcd-d78ce445122a.png)

**Comment by Lap0u** [comment]
32507048781379427d3553a27828c1b70e6bffc3
Fix les deux prob, verifier si trop d'arguments affiche exit sans exit

**Comment by Lap0u** [comment]
verifs ok
