### ISSUE TITLE
`unset` does not return an error 

### ISSUE THREAD

**Issue by OlgaKush512** [Lap0u/minishell#53]
![image](https://user-images.githubusercontent.com/92527601/145724499-7ff1eee5-b369-45fb-aab2-88a944f4e45d.png)
Should be 0.

**Comment by Lap0u** [comment]
c713ee15ad43f69f332c998b22c01f50e735d26c
Fix return quand le mot est bon mais qu'il n'existe pas dans env, renvoie 0
